trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Import variable group you created in Library
variables:
- group: New variable group 08-Sep

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

# Install Ansible + AWS Collection + boto3
- script: |
    pip install ansible boto3 botocore amazon.aws
  displayName: 'Install Ansible and AWS dependencies'

# Run Ansible Playbook for AWS
- script: |
    ansible-playbook -i localhost, \
      -e aws_access_key=$(AWS_ACCESS_KEY_ID) \
      -e aws_secret_key=$(AWS_SECRET_ACCESS_KEY) \
      azure_poc_aws_playbook.yml
  displayName: 'Run Ansible Playbook for AWS'
