trigger:
- master

pool:
  name: Default   # your self-hosted agent

variables:
- group: New variable group 08-Sep

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install ansible boto3 botocore amazon.aws
  displayName: 'Install Ansible and AWS dependencies'

- script: |
    ansible-playbook -i localhost, \
      -e aws_access_key=$(AWS_ACCESS_KEY_ID) \
      -e aws_secret_key=$(AWS_SECRET_ACCESS_KEY) \
      azure_poc_aws_playbook.yml
  displayName: 'Run Ansible Playbook for AWS'
